Build mkinitfs version 3.8.1 from source
Alpine 3.16 has nlplug-findfs tool in mkinitfs package that has very small buffer for uevents and
cannot detect file system on some devices with many PCIe devices

Here we build the package from Alpine 3.18 from source

Signed-off-by: Mikhail Malyshev <mikem@zededa.com>

diff --git a/pkg/mkimage-raw-efi/Dockerfile b/pkg/mkimage-raw-efi/Dockerfile
--- a/pkg/mkimage-raw-efi/Dockerfile
+++ b/pkg/mkimage-raw-efi/Dockerfile
@@ -1,3 +1,4 @@
+# syntax=docker/dockerfile-upstream:1.5.0-rc2-labs
 # This mkimage-raw-efi produces the raw EFI partition for EVE,
 # including the files in efi-files in the image.  This includes:
 #
@@ -6,9 +7,19 @@
 #
 FROM lfedge/eve-alpine:9fb9b9cbf7d90066a70e4704d04a6fe248ff52bb AS build
 SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
-ENV BUILD_PKGS mkinitfs grep patch
-ENV PKGS mtools dosfstools libarchive-tools sgdisk e2fsprogs util-linux squashfs-tools coreutils tar dmidecode
+ENV BUILD_PKGS grep patch git make gcc linux-headers musl-dev autoconf automake pkgconfig kmod-dev util-linux-dev cryptsetup-dev lddtree libgcc
+ENV PKGS mtools dosfstools libarchive-tools sgdisk e2fsprogs util-linux squashfs-tools coreutils tar dmidecode \
+    kmod-libs cryptsetup-libs libblkid
 RUN eve-alpine-deploy.sh
+
+# get mkinitfs source from git and build it locally
+# it depends on mod-libs cryptsetup-libs libblkid at runtime and lddtree to run mkinitfs itself
+# we could build APK file ourselves but 'apk add' would failed because networking is disabled for almost all linuxkit images
+WORKDIR /tmp/mkinitfs
+ADD https://github.com/alpinelinux/mkinitfs.git#3.8.1 /tmp/mkinitfs
+RUN make -j "$(getconf _NPROCESSORS_ONLN)"
+WORKDIR /
+RUN make -C /tmp/mkinitfs install
 
 WORKDIR /out
 RUN echo "mtools_skip_check=1" >> etc/mtools.conf
@@ -32,6 +43,16 @@ RUN mv rootfs /out
 WORKDIR /
 COPY initramfs-init.patch /tmp/
 RUN patch -p1 < /tmp/initramfs-init.patch
+
+# from https://git.alpinelinux.org/aports/tree/main/mkinitfs/mkinitfs.post-install?id=7b64ec6e904040bd75ea21529b4fce61c908a553
+# we need to simulate mkinitfs.post-install from the original APK file
+# --- Quote ---
+# safety. if nlplug-findfs is missing in the initramfs image we may end up
+# with an unbootable system.
+RUN if ! grep -q -w /sbin/nlplug-findfs  /etc/mkinitfs/features.d/base.files; then \
+        echo "/sbin/nlplug-findfs" >> /etc/mkinitfs/features.d/base.files; \
+    fi
+
 RUN echo /bin/grep >> /etc/mkinitfs/features.d/base.files
 RUN mkinitfs -n -o /out/initrd.img
 
