Customizing Alpine initramfs scripts for our needs
Signed-off-by: Roman Shaposhnik <rvs@zededa.com>

diff --git a/pkg/mkimage-raw-efi/initramfs-init b/pkg/mkimage-raw-efi/initramfs-init
--- a/pkg/mkimage-raw-efi/initramfs-init
+++ b/pkg/mkimage-raw-efi/initramfs-init
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # this is the init script version
-VERSION=@VERSION@
+VERSION=3.3.0-EVE
 SINGLEMODE=no
 sysroot=/sysroot
 splashfile=/.splash.ctrl
@@ -334,7 +334,7 @@ myopts="alpine_dev autodetect autoraid chart cryptroot cryptdm cryptheader crypt
 	cryptdiscards cryptkey debug_init dma init init_args keep_apk_new modules ovl_dev
 	pkgs quiet root_size root usbdelay ip alpine_repo apkovl alpine_start splash
 	blacklist overlaytmpfs rootfstype rootflags nbd resume s390x_net dasd ssh_key
-	BOOTIF"
+	BOOTIF setup_loops eve_installer"
 
 for opt; do
 	case "$opt" in
@@ -346,7 +346,7 @@ for opt; do
 
 	for i in $myopts; do
 		case "$opt" in
-		$i=*)	eval "KOPT_${i}=${opt#*=}";;
+		$i=*)	eval "KOPT_${i}"='${opt#*=}';;
 		$i)	eval "KOPT_${i}=yes";;
 		no$i)	eval "KOPT_${i}=no";;
 		esac
@@ -469,6 +469,37 @@ fi
 
 # zpool reports /dev/zfs missing if it can't read /etc/mtab
 ln -s /proc/mounts /etc/mtab
+
+# check if setup_loops=... was set
+if [ -n "$KOPT_setup_loops" ]; then
+	# locate boot media and mount it
+	ebegin "Mounting boot media"
+	nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
+		${KOPT_usbdelay:+-t $(( $KOPT_usbdelay * 1000 ))} \
+		-n -r /tmp/rootfs
+	eend $?
+
+        # now add loops
+	ebegin "Setting up loopback block devices"
+	for l in $(cat /tmp/rootfs); do
+		losetup -r -f "$l"
+	done
+	eend $?
+fi
+
+# check if eve_installer=... was set
+if [ -n "$KOPT_eve_installer" ]; then
+        [ -n "$KOPT_debug_init" ] && export DEBUG=yes
+	ebegin "Lauhcning EVE installer."
+	/install
+        eend $?
+
+        # in a normal scenario we never get to this point
+        # since installer is expected to shut down the
+        # system on success, but if something goes wrong...
+        echo "Installation failed. Entering single mode. 'exit' this shell with care."
+	sh
+fi
 
 # check if root=... was set
 if [ -n "$KOPT_root" ]; then
