mkimage-raw-efi: Bump Alpine version to 3.20
- Bump mkinitfs to 3.10.1 (Alpine's 3.20 version)

Signed-off-by: Renê de Souza Pinto <rene@renesp.com.br>

diff --git a/pkg/mkimage-raw-efi/initramfs-init.patch b/pkg/mkimage-raw-efi/initramfs-init.patch
--- a/pkg/mkimage-raw-efi/initramfs-init.patch
+++ b/pkg/mkimage-raw-efi/initramfs-init.patch
@@ -1,60 +1,60 @@
---- a/usr/share/mkinitfs/initramfs-init
-+++ b/usr/share/mkinitfs/initramfs-init
+--- /usr/share/mkinitfs/initramfs-init
++++ initramfs-init
 @@ -1,7 +1,7 @@
  #!/bin/sh
  
  # this is the init script version
--VERSION=3.8.1
-+VERSION=3.8.1-EVE
+-VERSION=3.10.1-r0
++VERSION=3.10.1-r0-EVE
  SINGLEMODE=no
  sysroot="$ROOT"/sysroot
  splashfile=/.splash.ctrl
-@@ -375,7 +375,7 @@ myopts="alpine_dev autodetect autoraid chart cryptroot cryptdm cryptheader crypt
- 	cryptdiscards cryptkey debug_init dma init init_args keep_apk_new modules ovl_dev
- 	pkgs quiet root_size root usbdelay ip alpine_repo apkovl alpine_start splash
- 	blacklist overlaytmpfs overlaytmpfsflags rootfstype rootflags nbd resume s390x_net
--	dasd ssh_key BOOTIF zfcp uevent_buf_size"
-+	dasd ssh_key BOOTIF zfcp uevent_buf_size find_boot"
+@@ -450,7 +450,7 @@
+ 	cryptdiscards cryptkey debug_init ds init init_args keep_apk_new modules
+ 	pkgs quiet root_size root usbdelay ip alpine_repo apkovl splash
+ 	blacklist overlaytmpfs overlaytmpfsflags rootfstype rootflags nbd resume resume_offset
+-	s390x_net dasd ssh_key BOOTIF zfcp uevent_buf_size aoe aoe_iflist aoe_mtu wireguard"
++	s390x_net dasd ssh_key BOOTIF zfcp uevent_buf_size aoe aoe_iflist aoe_mtu wireguard find_boot"
  
  for opt; do
  	case "$opt" in
-@@ -533,13 +533,64 @@ fi
+@@ -635,14 +635,64 @@
  # zpool reports /dev/zfs missing if it can't read /etc/mtab
  ln -s /proc/mounts "$ROOT"/etc/mtab
  
 +# let's see if we were told to identify a boot partition
 +if [ -n "$KOPT_find_boot" ]; then
-+		# locate boot media and mount it
-+		# NOTE that we may require up to 3 tries with
-+		# 30 seconds pauses between them to accomodate
-+		# really slow controllers (such as bad USB sticks)
-+		for i in 0 1 2; do
-+				ebegin "Attempt $i to find and mount boot media"
-+				MEDIA_ID=$(grep -l "$KOPT_find_boot" /media/*/boot/.uuid 2>/dev/null)
-+				if [ -n "$MEDIA_ID" ]; then
-+						mkdir -p /media/boot
-+						$MOCK mount --bind "/media/$(echo "$MEDIA_ID" | cut -f3 -d/)" /media/boot
-+						break
-+				fi
-+				sleep $(( i * 30 ))
-+				$MOCK nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
-+					${KOPT_usbdelay:+-t $(( $KOPT_usbdelay * 1000 ))} \
-+					${KOPT_uevent_buf_size:+-U $KOPT_uevent_buf_size} \
-+					-n -b $repofile -a /tmp/apkovls
-+				eend $?
-+		done
++	# locate boot media and mount it
++	# NOTE that we may require up to 3 tries with
++	# 30 seconds pauses between them to accomodate
++	# really slow controllers (such as bad USB sticks)
++	for i in 0 1 2; do
++		 ebegin "Attempt $i to find and mount boot media"
++		 MEDIA_ID=$(grep -l "$KOPT_find_boot" /media/*/boot/.uuid 2>/dev/null)
++		 if [ -n "$MEDIA_ID" ]; then
++			  mkdir -p /media/boot
++			  $MOCK mount --bind "/media/$(echo "$MEDIA_ID" | cut -f3 -d/)" /media/boot
++			  break
++		 fi
++		 sleep $(( i * 30 ))
++		 $MOCK nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
++		         ${KOPT_usbdelay:+-t $(( $KOPT_usbdelay * 1000 ))} \
++		         ${KOPT_uevent_buf_size:+-U $KOPT_uevent_buf_size} \
++		         -n -b $repofile -a /tmp/apkovls
++		 eend $?
++	done
 +
-+		# if we didn't find anything, but were asked to -- treat it
-+		# as an error condition (it maybe transient, but it needs to
-+		# be corrected
-+		if [ -z "$MEDIA_ID" ]; then
-+				echo "Failed to identify boot media. Try to re-run nlplug-findfs manually to see what's wrong:"
-+				echo "  nlplug-findfs -p /sbin/mdev -d -t 30000 -n  -n -b $repofile -a /tmp/apkovls"
-+				echo "once you find boot device, run:"
-+				echo "  mount --bind /media/XXX /media/boot"
-+				echo "and then exit the shell."
-+				sh
-+		fi
++	# if we didn't find anything, but were asked to -- treat it
++	# as an error condition (it maybe transient, but it needs to
++	# be corrected
++	if [ -z "$MEDIA_ID" ]; then
++		 echo "Failed to identify boot media. Try to re-run nlplug-findfs manually to see what's wrong:"
++		 echo "  nlplug-findfs -p /sbin/mdev -d -t 30000 -n  -n -b $repofile -a /tmp/apkovls"
++		 echo "once you find boot device, run:"
++		 echo "  mount --bind /media/XXX /media/boot"
++		 echo "and then exit the shell."
++		 sh
++	fi
 +fi
 +
  # check if root=... was set
@@ -64,47 +64,47 @@
 -	$MOCK nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
 -		${KOPT_uevent_buf_size:+-U $KOPT_uevent_buf_size} \
 -		$KOPT_root
-+	if [ -f "$KOPT_root" ]; then
-+			LOOP_IMG=$(realpath "$KOPT_root")
-+			# workingaround linux kernel's desire to lump the entire
-+			# set of initrd images into /initrd.image
-+			if [ "$LOOP_IMG" = /initrd.image ]; then
-+					OFFSET=$(LANG=C grep -obUaP hsqs /initrd.image|cut -f1 -d:|head -1)
-+					if [ -n "$OFFSET" ]; then
-+							LOSETUP_EXTRA_OPTS="-o$OFFSET"
-+					fi
-+			fi
-+
-+			KOPT_root=$(losetup -f)
-+			losetup $LOSETUP_EXTRA_OPTS -r -f "$LOOP_IMG"
++        if [ -f "$KOPT_root" ]; then
++	        LOOP_IMG=$(realpath "$KOPT_root")
++	        # workingaround linux kernel's desire to lump the entire
++	        # set of initrd images into /initrd.image
++	        if [ "$LOOP_IMG" = /initrd.image ]; then
++		         OFFSET=$(LANG=C grep -obUaP hsqs /initrd.image|cut -f1 -d:|head -1)
++		         if [ -n "$OFFSET" ]; then
++			          LOSETUP_EXTRA_OPTS="-o$OFFSET"
++		         fi
++	        fi
+ 
++	        KOPT_root=$(losetup -f)
++	        losetup $LOSETUP_EXTRA_OPTS -r -f "$LOOP_IMG"
 +	else
-+			$MOCK nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
-+				${KOPT_uevent_buf_size:+-U $KOPT_uevent_buf_size} \
-+				$KOPT_root
++		$MOCK nlplug-findfs $cryptopts -p /sbin/mdev ${KOPT_debug_init:+-d} \
++			${KOPT_uevent_buf_size:+-U $KOPT_uevent_buf_size} \
++			$KOPT_root
 +	fi
 +
- 
  	if [ "$SINGLEMODE" = "yes" ]; then
  		echo "Entering single mode. Type 'exit' to continue booting."
-@@ -573,13 +624,15 @@ if [ -n "$KOPT_root" ]; then
+ 		sh
+@@ -678,13 +728,15 @@
  		$MOCK mount ${KOPT_rootfstype:+-t $KOPT_rootfstype} -o $rootflags \
  			$KOPT_root /media/root-ro
  		# Mount writable overlay tmpfs
 -		overlaytmpfsflags="mode=0755,${KOPT_overlaytmpfsflags:+$KOPT_overlaytmpfsflags,}rw"
 -		$MOCK mount -t tmpfs -o $overlaytmpfsflags root-tmpfs /media/root-rw
-+		# overlaytmpfsflags="mode=0755,${KOPT_overlaytmpfsflags:+$KOPT_overlaytmpfsflags,}rw"
-+		# $MOCK mount -t tmpfs -o $overlaytmpfsflags root-tmpfs /media/root-rw
++		#overlaytmpfsflags="mode=0755,${KOPT_overlaytmpfsflags:+$KOPT_overlaytmpfsflags,}rw"
++		#$MOCK mount -t tmpfs -o $overlaytmpfsflags root-tmpfs /media/root-rw
  		# Create additional mountpoints and do the overlay mount
  		mkdir -p /media/root-rw/work /media/root-rw/root
  		$MOCK mount -t overlay -o \
  			lowerdir=/media/root-ro,upperdir=/media/root-rw/root,workdir=/media/root-rw/work \
  			overlayfs $sysroot
 +		# this protects /media/root-rw from being destroyed by switch_root
-+		$MOCK mount -t proc proc /media/root-rw			
++		$MOCK mount -t proc proc /media/root-rw
  	else
  		if [ "$rootfstype" = "zfs" ]; then
  			prepare_zfs_root
-@@ -590,7 +643,7 @@ if [ -n "$KOPT_root" ]; then
+@@ -695,7 +747,7 @@
  	fi
  
  	eend $?
