support multiple disks in installer
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

diff --git a/pkg/mkimage-raw-efi/install b/pkg/mkimage-raw-efi/install
--- a/pkg/mkimage-raw-efi/install
+++ b/pkg/mkimage-raw-efi/install
@@ -68,7 +68,7 @@ root_dev() {
 
 # find_part LABEL BLOCK_DEV
 find_part() {
-   PARTS=$(lsblk -anl -o "NAME,PARTLABEL" 2>/dev/null | sed -ne "/$1"'$/s#'"$1##p")
+   PARTS=$(lsblk -anl -o "NAME,PARTLABEL" 2>/dev/null | sed -ne "/$1"'$/s#'"[[:space:]]*$1##p")
    for p in $PARTS ; do
       [ -f "/sys/block/$2/$p/dev" ] && echo "$p" && exit 0
    done
@@ -97,6 +97,26 @@ collect_black_box() {
    tar -C /run/CONFIG -cjf "$1/config.tar.bz2" .
    tar -C /run/P3 -cjf "$1/persist.tar.bz2" status newlog log config checkpoint certs agentdebug
    tpmmgr saveTpmInfo "$1"/tpminfo.txt
+}
+
+# prepare_mounts_and_zfs_pool POOL_CREATION_COMMAND_SUFFIX_SUFFIX
+prepare_mounts_and_zfs_pool() {
+  [ -e /root/sys ] || mkdir /root/sys && mount -t sysfs sysfs /root/sys
+  [ -e /root/proc ] || mkdir /root/proc && mount -t proc proc /root/proc
+  [ -e /root/dev ] || mkdir /root/dev && mount -t devtmpfs -o size=10m,nr_inodes=248418,mode=755,nosuid,noexec,relatime devtmpfs /root/dev
+  [ -e /root/run ] || mkdir /root/run && mount --rbind /run /root/run
+  POOL_CREATION_COMMAND="chroot /root zpool create -f -m none -o feature@encryption=enabled -O overlay=on persist $1"
+  eval "$POOL_CREATION_COMMAND"
+  chroot /root zfs set mountpoint="/run/P3" persist
+}
+
+adjust_zfs_mounts_and_umount() {
+  chroot /root zfs set mountpoint="/persist" persist
+  chroot /root zfs create -p -o mountpoint="/persist/containerd/io.containerd.snapshotter.v1.zfs" persist/snapshots
+  umount /root/sys ||:
+  umount /root/proc ||:
+  umount /root/dev ||:
+  umount /root/run ||:
 }
 
 # do this just in case
@@ -138,7 +158,7 @@ fi
 [ -z "$INSTALL_DEV" ] && bail "FATAL: didn't find a single free disk"
 
 # we allow for P3 partition to reside on a separate disk
-INSTALL_PERSIST=`cat /proc/cmdline | tr ' ' '\012' | sed -ne '/^eve_persist_disk=/s#^.*=##p'`
+INSTALL_PERSIST=$(</proc/cmdline tr ' ' '\012' | sed -ne '/^eve_persist_disk=/s#^.*=##p')
 INSTALL_PERSIST=${INSTALL_PERSIST:-$INSTALL_DEV}
 
 # now lets figure out whether we have installation material
@@ -170,24 +190,84 @@ done
 # we may be asked to pause before install procedure
 grep -q eve_pause_before_install /proc/cmdline && pause "formatting the /dev/$INSTALL_DEV"
 
-# FIXME: gross hack to allow P3 partition on a disk different from a bootable one
-# this needs to go away the moment we implement LVM or ZFS
+P3_ON_BOOT_PLACEHOLDER="P3_ON_BOOT_PLACEHOLDER"
+POOL_CREATION_COMMAND_SUFFIX=""
+DISK_WITH_P3=""
+DISKS_TO_MERGE_COUNT=0
+MULTIPLE_DISKS=false
 if [ "$INSTALL_DEV" != "$INSTALL_PERSIST" ]; then
-   # apparently sgdisk -Z doesn't clear MBR and keeps complaining
-   PDEV="/dev/$INSTALL_PERSIST"
-   dd if=/dev/zero of="$PDEV" bs=512 count=1 conv=notrunc
-   sgdisk -Z --clear "$PDEV" 2>/dev/null || :
-   sgdisk --new 1:2048:0 --typecode=1:5f24425a-2dfa-11e8-a270-7b663faccc2c --change-name=1:P3 "$PDEV"
-   sgdisk -v "$PDEV"
-   # force make-raw to skip persist
-   MAKE_RAW_PARTS="efi imga imgb conf"
+   if echo "$INSTALL_PERSIST"| grep -q ","; then
+     MULTIPLE_DISKS=true
+     modprobe zfs
+     MAKE_RAW_PARTS="efi imga imgb conf"
+     IFS=',' ;for dev in $INSTALL_PERSIST; do
+        if [ "$dev" = "$INSTALL_DEV" ]; then
+           # in case we want to have one of P3 on the bootable disk
+           MAKE_RAW_PARTS="efi imga imgb conf persist"
+           DISK_WITH_P3="$dev"
+           POOL_CREATION_COMMAND_SUFFIX="$POOL_CREATION_COMMAND_SUFFIX $P3_ON_BOOT_PLACEHOLDER"
+           DISKS_TO_MERGE_COUNT=$((DISKS_TO_MERGE_COUNT+1))
+        else
+           if [ -f "/sys/block/$dev/dev" ]; then
+              PDEV="/dev/$dev"
+              dd if=/dev/zero of="$PDEV" bs=512 count=1 conv=notrunc && sync
+              sgdisk -Z --clear "$PDEV" 2>/dev/null || :
+              POOL_CREATION_COMMAND_SUFFIX="$POOL_CREATION_COMMAND_SUFFIX $PDEV"
+              DISKS_TO_MERGE_COUNT=$((DISKS_TO_MERGE_COUNT+1))
+           else
+              echo "WARNING: Cannot find /sys/block/$dev/dev, will skip it"
+           fi
+        fi
+     done
+     if [ $DISKS_TO_MERGE_COUNT -eq 0 ]; then
+          # in case of only comma provided
+          MAKE_RAW_PARTS="efi imga imgb conf persist"
+          DISK_WITH_P3="$INSTALL_DEV"
+          POOL_CREATION_COMMAND_SUFFIX=$P3_ON_BOOT_PLACEHOLDER
+          DISKS_TO_MERGE_COUNT=1
+     fi
+   else
+     # apparently sgdisk -Z doesn't clear MBR and keeps complaining
+     PDEV="/dev/$INSTALL_PERSIST"
+     dd if=/dev/zero of="$PDEV" bs=512 count=1 conv=notrunc
+     sgdisk -Z --clear "$PDEV" 2>/dev/null || :
+     sgdisk --new 1:2048:0 --typecode=1:5f24425a-2dfa-11e8-a270-7b663faccc2c --change-name=1:P3 "$PDEV"
+     sgdisk -v "$PDEV"
+     # force make-raw to skip persist
+     MAKE_RAW_PARTS="efi imga imgb conf"
+   fi
 fi
 
 # do the install (unless we're only here to collect the black box)
 grep -q eve_blackbox /proc/cmdline || /make-raw "/dev/$INSTALL_DEV" $MAKE_RAW_PARTS || bail "Installation failed. Entering shell..."
 
-# now the disk is ready - mount partitions
-mount_part P3 "$INSTALL_DEV" 2>/dev/null
+if [ "$MULTIPLE_DISKS" = true ]; then
+  if [ "$DISK_WITH_P3" != "" ]; then
+    P3_ID="$(find_part P3 "$DISK_WITH_P3")"
+    [ -z "$P3_ID" ] && bail "Installation failed. Cannot found P3. Entering shell..."
+    POOL_CREATION_COMMAND_SUFFIX=$(echo "$POOL_CREATION_COMMAND_SUFFIX" | sed "s#$P3_ON_BOOT_PLACEHOLDER#/dev/$P3_ID#g")
+    echo "WARNING: Will use /dev/$P3_ID instead of /dev/$DISK_WITH_P3 for P3 because of bootable parts needed"
+  fi
+  # we use mirror for 2 disks, raidz1 for 3 disks and raidz2 for more than 3 disks
+  case $DISKS_TO_MERGE_COUNT in
+    1) ;;
+    2)
+      POOL_CREATION_COMMAND_SUFFIX="mirror $POOL_CREATION_COMMAND_SUFFIX"
+      ;;
+    3)
+      POOL_CREATION_COMMAND_SUFFIX="raidz1 $POOL_CREATION_COMMAND_SUFFIX"
+      ;;
+    *)
+      POOL_CREATION_COMMAND_SUFFIX="raidz2 $POOL_CREATION_COMMAND_SUFFIX"
+      ;;
+  esac
+  prepare_mounts_and_zfs_pool "$POOL_CREATION_COMMAND_SUFFIX"
+else
+  # now the disk is ready - mount partitions
+  mount_part P3 "$INSTALL_DEV" 2>/dev/null
+fi
+
+
 if mount_part CONFIG "$INSTALL_DEV" -t vfat -o iocharset=iso8859-1; then
    # uuidgen | sed -e 's#^.*-##'
    SOFT_SERIAL=$(tr ' ' '\012' < /proc/cmdline | sed -n '/eve_soft_serial=/s#eve_soft_serial=##p')
@@ -208,13 +288,17 @@ if mount_part INVENTORY "$(root_dev)" -t vfat -o iocharset=iso8859-1; then
 fi
 
 # we also maybe asked to pause after
-grep -q eve_pause_after_install /proc/cmdline && pause "before shutting the node down"
+grep -q eve_pause_after_install /proc/cmdline && pause "shutting the node down"
 
 # lets hope this is enough to flush the caches
 sync; sleep 5; sync
 for p in CONFIG INVENTORY P3; do
    umount "/run/$p" 2>/dev/null
 done
+
+if [ "$MULTIPLE_DISKS" = true ]; then
+   adjust_zfs_mounts_and_umount
+fi
 
 # we need a copy of these in tmpfs so that a block device with rootfs can be yanked
 cp /sbin/poweroff /sbin/reboot /bin/sleep /run
