add RoL Rpi4 test steps to eden GCP workflow
Signed-off-by: Aleksandrov Dmitriy <goodmobiledevices@gmail.com>

diff --git a/.github/workflows/eden_gcp.yml b/.github/workflows/eden_gcp.yml
--- a/.github/workflows/eden_gcp.yml
+++ b/.github/workflows/eden_gcp.yml
@@ -13,6 +13,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        backend: ["gcp", "rol"]
         hv: ["kvm", "xen"]
     steps:
       - name: Check
@@ -26,25 +27,37 @@ jobs:
                 echo "$addr overlaps with vpn"; exit 1
               fi
           done
-      - name: setup packages
+      - name: Check RoL secrets
+        if: matrix.backend == 'rol'
+        run: |
+          if [ -z "$ROL_API_URL" ]; then echo "::error::ROL_API_URL is empty" && exit 1; fi
+          if [ -z "$ROL_API_KEY" ]; then echo "::error::ROL_API_KEY is empty" && exit 1; fi
+          if [ -z "$ROL_PROJECT" ]; then echo "::error::ROL_PROJECT is empty" && exit 1; fi
+          if [ -z "$ROL_OVPN_CONF_BASE64" ]; then echo "::error::ROL_OVPN_CONF_BASE64 is empty" && exit 1; fi
+        env:
+          ROL_API_URL: ${{ secrets.ROL_API_URL }}
+          ROL_API_KEY: ${{ secrets.ROL_API_KEY }}
+          ROL_PROJECT: ${{ secrets.ROL_PROJECT }}
+          ROL_OVPN_CONF_BASE64: ${{ secrets.ROL_OVPN_CONF_BASE64 }}
+      - name: Setup packages
         run: |
           sudo apt update
-          sudo apt install -y qemu-utils openvpn curl jq
-          echo "$OVPN_FILE" | base64 -d > ./config.ovpn
-        env:
-          OVPN_FILE: ${{ secrets.OVPN_FILE }}
-      - name: Set up Cloud SDK
+          sudo apt install -y qemu binfmt-support qemu-user-static qemu-system-x86 qemu-system-aarch64 qemu-utils openvpn curl jq
+      - name: GCP Set up Google Cloud SDK
+        if: matrix.backend == 'gcp'
         uses: google-github-actions/setup-gcloud@master
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
       - id: 'gcpauth'
-        name: Auth to Google Cloud SDK
+        if: matrix.backend == 'gcp'
+        name: GCP Auth to Google Cloud SDK
         uses: google-github-actions/auth@v0.4.1
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           credentials_json: ${{ secrets.GCP_SA_KEY }}
           create_credentials_file: true
-      - name: clean
+      - name: GCP Clean
+        if: matrix.backend == 'gcp'
         run: |
           gcloud compute instances delete eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -q --zone=us-west1-a || echo "Does not exist"
           gcloud compute images delete eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -q || echo "Does not exist"
@@ -52,47 +65,73 @@ jobs:
         id: connect_vpn
         timeout-minutes: 1
         run: |
-          sudo openvpn --config ./config.ovpn --daemon
+          echo "$OVPN_GCP_FILE" | base64 -d > ./config_gcp.ovpn
+          echo "$OVPN_ROL_FILE" | base64 -d > ./config_rol.ovpn
+          sudo openvpn --config ./config_${{ matrix.backend }}.ovpn --daemon
           until ip -f inet addr show tun0; do sleep 5; ip a; done
           echo ::set-output name=tunnel_ip::$(ip -f inet addr show tun0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
-      - name: get eve
+        env:
+          OVPN_GCP_FILE: ${{ secrets.OVPN_FILE }}
+          OVPN_ROL_FILE: ${{ secrets.ROL_OVPN_CONF_BASE64 }}
+      - name: Get EVE
         uses: actions/checkout@v2
         with:
           path: 'eve'
-      - name: prepare eden
+      - name: Prepare eden
         run: |
-          if [ -f ${{ github.workspace }}/eve/tests/eden/eden-version ]; then
+          if [ "${{ matrix.backend }}" == "rol" ]; then
+            EDEN_VERSION=lfedge/eden:0.4.0
+          elif [ -f ${{ github.workspace }}/eve/tests/eden/eden-version ]; then
             EDEN_VERSION=$(cat ${{ github.workspace }}/eve/tests/eden/eden-version)
           else
             EDEN_VERSION=lfedge/eden:30c8b3f
           fi
           docker run -v $PWD:/out $EDEN_VERSION cp -a /eden/. /out/
           sudo chown -R $(whoami) .
-          ./eden config add default
-      - name: setup
+      - name: Eden setup
         run: |
-          export ipv4=`curl https://api.ipify.org/?format=json | jq ".ip" -r`
-          ./eden config add default --devmodel GCP
+          devmodel="--devmodel GCP"; [ "${{ matrix.backend }}" == "rol" ] && devmodel="--devmodel general --arch=arm64"
+          setup_flags="-v debug $([ "${{ matrix.backend }}" == "gcp" ] || echo "--netboot=true")"
+          eval ./eden config add default $devmodel
           ./eden config set default --key eve.tag --value="snapshot"
           ./eden config set default --key eve.hv --value ${{ matrix.hv }}
           ./eden config set default --key eve.tpm --value true
           ./eden config set default --key adam.eve-ip --value ${{ steps.connect_vpn.outputs.tunnel_ip }}
           ./eden config set default --key registry.ip --value ${{ steps.connect_vpn.outputs.tunnel_ip }}
           ./eden config set default --key=eden.tests --value=${{ github.workspace }}/eve/tests/eden
+          eval ./eden setup "$setup_flags"
+          ./eden start
+      - name: GCP Create VM
+        if: matrix.backend == 'gcp'
+        run: |
+          export ipv4=`curl https://api.ipify.org/?format=json | jq ".ip" -r`
           ./eden utils gcp firewall --source-range $ipv4/32 --name eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -k "${{ steps.gcpauth.outputs.credentials_file_path }}"
-          ./eden setup -v debug
           ./eden utils gcp image --image-name eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -k "${{ steps.gcpauth.outputs.credentials_file_path }}" upload
           ./eden utils gcp vm --image-name eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} --vm-name eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -k "${{ steps.gcpauth.outputs.credentials_file_path }}" run
-          ./eden start
           sleep 100
           BWD=$(./eden utils gcp vm get-ip --vm-name eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -k "${{ steps.gcpauth.outputs.credentials_file_path }}") || { echo "no IP, probably VM does not exist"; exit 1; }
           echo "the IP is $BWD"
           ./eden utils gcp firewall -k "${{ steps.gcpauth.outputs.credentials_file_path }}" --source-range $BWD --name edengcp-actions-${{ matrix.hv }}-${{github.run_number}} || { echo "cannot set firewall"; exit 1; }
+      - name: RoL rent RPi4
+        id: rol
+        if: matrix.backend == 'rol'
+        timeout-minutes: 60
+        run: |
+          rent_id=$(./eden rol rent create -p "$ROL_PROJECT" -m raspberry --model pi_4_model_b_8gb -n GHAction-${{ github.run_number }}-snapshot-${{ matrix.hv }})
+          echo ::set-output name=id::$(echo $rent_id)
+          until [[ "$(./eden rol rent get -p "$ROL_PROJECT" -i $rent_id | jq -r .machineState)" == "Ready" ]]; do sleep 10; echo "Waiting for EVE to load"; done
+        env:
+          ROL_API_URL: ${{ secrets.ROL_API_URL }}
+          ROL_API_KEY: ${{ secrets.ROL_API_KEY }}
+          ROL_PROJECT: ${{ secrets.ROL_PROJECT }}
+      - name: Eden EVE onboard
+        run: |
           ./eden eve onboard
-          echo > tests/workflow/testdata/eden_stop.txt
       - name: Test
         run: |
-          EDEN_TEST=gcp ./eden test ${{ github.workspace }}/eve/tests/eden/workflow -v debug
+          echo > tests/workflow/testdata/eden_stop.txt
+          if [ "${{ matrix.backend }}" == "gcp" ]; then export EDEN_TEST=gcp; fi
+          ./eden test ${{ github.workspace }}/eve/tests/eden/workflow -v debug
       - name: Collect logs
         if: ${{ always() }}
         run: |
@@ -121,13 +160,22 @@ jobs:
           echo "$(jq -s 'map(select(.content | contains("segfault at")))' trace.log)"|tee segfaults.log
           [ "$(jq length segfaults.log)" -gt 0 ] && echo "::warning::segfaults found, you can see them in Log counting->Segfaults section"
           echo "::endgroup::"
-      - name: Clean
+      - name: GCP Clean
         if: ${{ always() }}
         run: |
           gcloud compute firewall-rules delete eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} || echo "Does not exist"
           gcloud compute firewall-rules delete edengcp-actions-${{ matrix.hv }}-${{github.run_number}} || echo "Does not exist"
           gcloud compute instances delete eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -q --zone=us-west1-a || echo "Does not exist"
           gcloud compute images delete eve-edengcp-actions-${{ matrix.hv }}-${{github.run_number}} -q || echo "Does not exist"
+      - name: RoL Clean
+        if: ${{ always() }}
+        run: |
+          if [ -z "${{ steps.rol.outputs.id }}" ]; then exit 0; fi
+          ./eden rol rent close -p $ROL_PROJECT -i ${{ steps.rol.outputs.id }}
+        env:
+          ROL_API_URL: ${{ secrets.ROL_API_URL }}
+          ROL_API_KEY: ${{ secrets.ROL_API_KEY }}
+          ROL_PROJECT: ${{ secrets.ROL_PROJECT }}
       - name: Store raw test results
         if: ${{ always() }}
         uses: actions/upload-artifact@v2
