manifest tool now requires jq to be happy
Signed-off-by: Roman Shaposhnik <rvs@zededa.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -23,24 +23,27 @@ jobs:
              docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
       - name: Build packages
         run: |
-          # FIXME: this needs to be updated in the build image
-          if [ "$(uname -m)" = aarch64 ]; then
-             sudo apt install -y jq || :
-             docker rmi -f `docker image ls -q` || :
-             docker system prune -f || :
-          fi
           # GH Actions convert our annotated tags into plain ones,
           # so we need to convert it back (but only if it exists).
           if [ -n "$(git tag)" ]; then
              git config --global user.name "Edge Virtualization Engine"
              git config --global user.email "eve@lfedge.org"
-             git tag -a -m"Release $(git tag)" -f $(git tag) $(git tag)
+             for t in $(git tag); do
+                git tag -a -m"Release $t" -f "$t" "$t"
+             done
           fi
           # sadly, our build sometimes times out on network access
-          # re-trying for 3 times if needed
+          # and running out of disk space: re-trying for 3 times
           for i in 1 2 3; do
              if make LINUXKIT_PKG_TARGET=push pkgs; then
                 break
+             else
+                # the most likely reason for 'make pkgs' to fail is
+                # the docker cache produced by the build exhausting
+                # disk space. So the following can't hurt before we
+                # retry:
+                docker rmi -f `docker image ls -q` || :
+                docker system prune -f || :
              fi
           done
       - name: Build EVE
