PKGS_SKIP option to skip unneeded pkgs from bulk build
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -57,8 +57,9 @@ jobs:
           fi
           # sadly, our build sometimes times out on network access
           # and running out of disk space: re-trying for 3 times
+          # we skip some additional packages to reduce disk space usage
           for i in 1 2 3; do
-             if make -e V=1 LINUXKIT_PKG_TARGET=push pkgs; then
+             if make -e V=1 PKGS_SKIP="eve|test-microsvcs|kvm-tools|k3s|acrn|acrn-kernel" LINUXKIT_PKG_TARGET=push pkgs; then
                 break
              else
                 # the most likely reason for 'make pkgs' to fail is
@@ -94,3 +95,50 @@ jobs:
         run: |
           rm -rf dist dist.xen
           make -e V=1 HV=mini LINUXKIT_PKG_TARGET=push eve
+  build-other-packages:
+    if: github.event.repository.full_name == 'lf-edge/eve'
+    runs-on: ${{ matrix.os }}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [arm64-secure, ubuntu-20.04]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Determine architecture prefix and ref
+        env:
+          REF: ${{ github.ref }}
+        run: |
+          echo "ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')" >> "$GITHUB_ENV"
+          echo "TAG=$(echo "$REF" | sed -e 's#^.*/##' -e 's#master#snapshot#' -e 's#main#snapshot#')" >> "$GITHUB_ENV"
+      - name: Login to DockerHUB
+        run: |
+          echo "${{ secrets.RELEASE_DOCKERHUB_TOKEN }}" |\
+             docker login -u "${{ secrets.RELEASE_DOCKERHUB_ACCOUNT }}" --password-stdin
+      - name: Build packages
+        run: |
+          # GH Actions convert our annotated tags into plain ones,
+          # so we need to convert it back (but only if it exists).
+          if [ -n "$(git tag)" ]; then
+             git config --global user.name "Edge Virtualization Engine"
+             git config --global user.email "eve@lfedge.org"
+             for t in $(git tag); do
+                git tag -a -m"Release $t" -f "$t" "$t"
+             done
+          fi
+          # sadly, our build sometimes times out on network access
+          # and running out of disk space: re-trying for 3 times
+          for i in 1 2 3; do
+             if make -e V=1 LINUXKIT_PKG_TARGET=push pkg/kvm-tools pkg/k3s pkg/acrn pkg/acrn-kernel; then
+                break
+             else
+                # the most likely reason for 'make pkgs' to fail is
+                # the docker cache produced by the build exhausting
+                # disk space. So the following can't hurt before we
+                # retry:
+                docker rmi -f `docker image ls -q` || :
+                docker system prune -f || :
+             fi
+          done
