Intorducing vtpmd service to bring fully virtualized TPM to the VMs
This commit brings SWTPM in EVE, in order to emulate Virtual TPM in
the VMS. To achive this we create a SWTPM instance per VM. The SWTPM
instance is configured to use a Unix Domain Socket as a communication line,
after passing the socket path to the QEMU virtual TPM configuration,
it automatically creates a virtual TPM device for the VM which is accessible
like a normal TPM device under /dev/tpm* .

SWTPM saves and loads the TPM state on/from the disk, so at the next VM
boot all the TPM keys, TPM NVRAM data, etc are present. In addition SWTPM
is configured to encrypt the TPM state files using a 256-bit AES key. We
use the same key as vault key, this key stored in TPM and access to it is
authorized using a PCR policy, this makes it easier to manage since if
we use a separate key for SWTPM states, there is one more key to
backup/restore from the controller.

Signed-off-by: Shahriyar Jalayeri <shahriyar@zededa.com>

diff --git a/pkg/vtpm/Dockerfile b/pkg/vtpm/Dockerfile
--- a/pkg/vtpm/Dockerfile
+++ b/pkg/vtpm/Dockerfile
@@ -5,9 +5,10 @@
 
 FROM shahzededa/eve-alpine:latest as build
 ENV BUILD_PKGS gcc g++ autoconf automake libtool make openssl-dev libtasn1-dev \
-               json-glib-dev gnutls bash expect gawk socat libseccomp-dev gmp-dev musl-utils
-ENV PKGS alpine-baselayout musl-utils glib gmp gnutls libtasn1 libseccomp musl \
-         strace libcrypto3 json-glib gdb
+               json-glib-dev gnutls bash expect gawk socat libseccomp-dev gmp-dev \
+               musl-utils autoconf-archive git json-c json-c-dev libcurl curl-dev \
+               patch go
+ENV PKGS libseccomp socat libcurl
 RUN eve-alpine-deploy.sh
 
 ADD https://github.com/stefanberger/libtpms.git#v0.9.6 /libtpms
@@ -24,11 +25,42 @@ RUN make -j$(nproc)
 RUN make -j$(nproc) install
 RUN cp /out/usr/lib/swtpm/* /out/usr/lib/
 
-#Pull a selected set of artifacts into the final stage.
-FROM scratch
-COPY --from=build /out /
-COPY init.sh /usr/bin/
-ENTRYPOINT []
-WORKDIR /
+WORKDIR /tpm2-tss
+ADD --keep-git-dir=true https://github.com/tpm2-software/tpm2-tss.git#4.0.1 /tpm2-tss
+RUN ./bootstrap && \
+    ./configure --disable-dependency-tracking && \
+    make -j$(nproc) && \
+    make install
+RUN cp /usr/local/lib/libtss2* /out/usr/lib/
 
+WORKDIR /tpm2-tools
+ADD --keep-git-dir=true https://github.com/tpm2-software/tpm2-tools.git#5.5 /tpm2-tools
+COPY patch/patch-tpm2-tools.diff .
+RUN patch -p1 < patch-tpm2-tools.diff
+RUN ./bootstrap && \
+    ./configure && \
+    make -j$(nproc)
+RUN cp lib/.libs/libcommon.so* /out/usr/lib/
+RUN cp tools/.libs/tpm2 /out/usr/bin/
+
+COPY src/  /build/.
+COPY go.mod /build/.
+COPY go.sum /build/.
+COPY vendor /build/vendor
+ARG GOPKGVERSION
+WORKDIR /build
+SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+# hadolint ignore=SC2046
+RUN echo "Running go vet" && go vet ./... && echo "Running go fmt" && \
+    ERR=$(gofmt -e -l -s $(find . -name \*.go | grep -v /vendor/)) && \
+    if [ -n "$ERR" ] ; then echo "go fmt Failed - ERR: $ERR"; exit 1 ; fi
+RUN GO111MODULE=on CGO_ENABLED=0 go build -ldflags "-s -w -X=main.Version=${GOPKGVERSION}" \
+    -mod=vendor -o /out/usr/bin/vtpmd .
+
+FROM scratch
+COPY --from=build /out/ /
+COPY init.sh /usr/bin/
+RUN mkdir /home && chown 101:101 /home
+WORKDIR /home
+ENTRYPOINT []
 CMD ["/usr/bin/init.sh"]
